---
output: 
  pdf_document:
    toc: false
    number_sections: false
    # includes:
    #   in_header: watermark.tex
params:
  filtered_daily_report_pos_player_summary: NA
  filtered_daily_report_pos: NA
  activity_date: NA
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[L]{Player Position Report}
  \fancyhead[R]{`r params$activity_date`}

  \thispagestyle{fancy}
  
---

```{r, include= FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r}
library(ggplot2)
library(gridExtra)
throw_load_plot <-   ggplot(params$filtered_daily_report_pos,
                            aes(x = period_instance, y = avg_throw_load)) +
        geom_bar(stat = "identity", fill = "steelblue") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
        scale_x_discrete(labels = function(x) sub("\\*_\\*.*", "", x)) +
  labs(
    y = "Throw Load",
    x = NULL,
    title = "Average Throw Load per Drill"
  ) +
  geom_text(
    aes(label = round(avg_throw_load)),  # Add count labels rounded to 1 decimal
    vjust = -0.5,                       # Position the label above the bar
    size = 3                            # Size of the text
  )
sprint_plot <- ggplot(params$filtered_daily_report_pos,
                          aes(x = period_instance, y = avg_sprint)) +
        geom_bar(stat = "identity", fill = "steelblue") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
        scale_x_discrete(labels = function(x) sub("\\*_\\*.*", "", x))+
  labs(
    y = "Sprint Distance",
    x = NULL,
    title = "Average Sprint Yards per Drill"
  ) +
  geom_text(
    aes(label = round(avg_sprint)),  # Add count labels rounded to 1 decimal
    vjust = -0.5,                       # Position the label above the bar
    size = 3                            # Size of the text
  )
lower_load_plot <- ggplot(params$filtered_daily_report_pos,
                          aes(x = period_instance, y = avg_lower_load)) +
        geom_bar(stat = "identity", fill = "steelblue") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
        scale_x_discrete(labels = function(x) sub("\\*_\\*.*", "", x))+
  labs(
    y = "Lower Body Load",
    x = NULL,
    title = "Average Lower Body Load per Drill"
  ) +
  geom_text(
    aes(label = round(avg_lower_load)),  # Add count labels rounded to 1 decimal
    vjust = -0.5,                       # Position the label above the bar
    size = 3                            # Size of the text
  )
swing_load_plot <- ggplot(params$filtered_daily_report_pos,
                          aes(x = period_instance, y = avg_swing_load)) +
        geom_bar(stat = "identity", fill = "steelblue") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
        scale_x_discrete(labels = function(x) sub("\\*_\\*.*", "", x))+
  labs(
    y = "Swing Load",
    x = NULL,
    title = "Average Swing Load per Drill"
  ) +
  geom_text(
    aes(label = round(avg_swing_load)),  # Add count labels rounded to 1 decimal
    vjust = -0.5,                       # Position the label above the bar
    size = 3                            # Size of the text
  )
```
```{r, fig.width=12, fig.height=16, out.width='100%', echo=FALSE}
library(gridExtra)
# g1<-grid.arrange(swing_load_plot, throw_load_plot, ncol = 2)
# g2 <-grid.arrange(lower_load_plot,sprint_plot, ncol = 1)
# grid.arrange(g1, g2, g2,ncol = 1)
g1 <- arrangeGrob(swing_load_plot, throw_load_plot, ncol = 2)
# g2 <- arrangeGrob(lower_load_plot, sprint_plot, ncol = 1)

grid.arrange(g1, lower_load_plot, sprint_plot, ncol = 1,
  heights = c(1, 1, 1))
```
\pagebreak
```{r}
temp_df <- params$filtered_daily_report_pos_player_summary
temp_df <- temp_df%>%
        select(athlete_name,
               sum_lower_load,
               sum_sprint,
               sum_swing_load,
               sum_throw_load,
               throw_intensity) %>%
        mutate(across(where(is.numeric), round, 0)) %>%
        rename(
          Athlete = athlete_name,
          `Lower Body Load` = sum_lower_load,
          `Sprint Distance` = sum_sprint,
          `Swing Load` = sum_swing_load,
          `Throw Load` = sum_throw_load,
          `Throw Intensity` = throw_intensity
        )
 
knitr::kable(temp_df) 

```

